-- Add missing store_config columns that exist in schema but not in database
ALTER TABLE "store_config" ADD COLUMN "email_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "email_from" text;
ALTER TABLE "store_config" ADD COLUMN "email_from_name" text;
ALTER TABLE "store_config" ADD COLUMN "email_reply_to" text;
ALTER TABLE "store_config" ADD COLUMN "email_recipients" text;
ALTER TABLE "store_config" ADD COLUMN "email_accent_color" text;
ALTER TABLE "store_config" ADD COLUMN "email_ticket_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_daily_report_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_weekly_report_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_stock_alert_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_refund_alert_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_expense_alert_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_security_alert_enabled" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_daily_report_time" text;
ALTER TABLE "store_config" ADD COLUMN "email_weekly_report_day" text;
ALTER TABLE "store_config" ADD COLUMN "email_weekly_report_time" text;
ALTER TABLE "store_config" ADD COLUMN "email_footer_text" text;
ALTER TABLE "store_config" ADD COLUMN "email_signature" text;
ALTER TABLE "store_config" ADD COLUMN "email_cc_recipients" text;
ALTER TABLE "store_config" ADD COLUMN "email_bcc_recipients" text;
ALTER TABLE "store_config" ADD COLUMN "email_subject_prefix" text;
ALTER TABLE "store_config" ADD COLUMN "email_digest_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "email_digest_interval_minutes" integer NOT NULL DEFAULT 60;
ALTER TABLE "store_config" ADD COLUMN "email_max_alerts_per_hour" integer NOT NULL DEFAULT 20;
ALTER TABLE "store_config" ADD COLUMN "email_auto_retry" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "email_max_retries" integer NOT NULL DEFAULT 3;
ALTER TABLE "store_config" ADD COLUMN "email_attach_pdf_ticket" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "email_attach_excel_report" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "email_monthly_report_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "email_monthly_report_day" integer NOT NULL DEFAULT 1;
ALTER TABLE "store_config" ADD COLUMN "ticket_template_venta" text;
ALTER TABLE "store_config" ADD COLUMN "ticket_template_proveedor" text;
ALTER TABLE "store_config" ADD COLUMN "ticket_design_venta" text;
ALTER TABLE "store_config" ADD COLUMN "ticket_design_corte" text;
ALTER TABLE "store_config" ADD COLUMN "ticket_design_proveedor" text;
ALTER TABLE "store_config" ADD COLUMN "clabe_number" text;
ALTER TABLE "store_config" ADD COLUMN "paypal_username" text;
ALTER TABLE "store_config" ADD COLUMN "paypal_qr_url" text;
ALTER TABLE "store_config" ADD COLUMN "cobrar_qr_url" text;
ALTER TABLE "store_config" ADD COLUMN "mp_device_id" text;
ALTER TABLE "store_config" ADD COLUMN "mp_public_key" text;
ALTER TABLE "store_config" ADD COLUMN "mp_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "conekta_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "conekta_public_key" text;
ALTER TABLE "store_config" ADD COLUMN "stripe_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "stripe_public_key" text;
ALTER TABLE "store_config" ADD COLUMN "clip_enabled" boolean NOT NULL DEFAULT false;
ALTER TABLE "store_config" ADD COLUMN "clip_api_key" text;
ALTER TABLE "store_config" ADD COLUMN "clip_serial_number" text;
ALTER TABLE "store_config" ADD COLUMN "servicios_provider" text NOT NULL DEFAULT 'local';
ALTER TABLE "store_config" ADD COLUMN "servicios_api_key" text;
ALTER TABLE "store_config" ADD COLUMN "servicios_api_secret" text;
ALTER TABLE "store_config" ADD COLUMN "servicios_sandbox" boolean NOT NULL DEFAULT true;
ALTER TABLE "store_config" ADD COLUMN "customer_display_message_style" text;
ALTER TABLE "store_config" ADD COLUMN "ai_provider" text NOT NULL DEFAULT 'openrouter';
ALTER TABLE "store_config" ADD COLUMN "ai_api_key_enc" text;
ALTER TABLE "store_config" ADD COLUMN "ai_model" text NOT NULL DEFAULT 'nvidia/nemotron-3-super:free';
ALTER TABLE "store_config" ADD COLUMN "inventory_general_columns" text NOT NULL DEFAULT '["title","sku","available","onHand"]';
ALTER TABLE "store_config" ADD COLUMN "default_margin" text NOT NULL DEFAULT '30';
ALTER TABLE "store_config" ADD COLUMN "default_starting_fund" numeric(10, 2) NOT NULL DEFAULT '500';
ALTER TABLE "store_config" ADD COLUMN "loyalty_expiration_days" integer NOT NULL DEFAULT 365;
ALTER TABLE "store_config" ADD COLUMN "exchange_rate_usd_mxn" numeric(10, 4) NOT NULL DEFAULT '17.5';
